### ISSUE TITLE
Cannot read state from IndexedDB after page refresh

### ISSUE THREAD

**Issue by HazyFish** [astoilkov/use-db#1]
The hook is unable to read the state out of the IndexDB if I refresh the page.

### Minimal Reproduction

```ts
  const [persistedTestData, setPersistedTestData] = useDb<number[]>(
    "PersistedTestData",
    {
      defaultValue: [],
      optimistic: true,
    }
  );

  useEffect(() => {
    const id = setInterval(() => {
      setPersistedTestData((prev) => [...prev, Date.now()]).catch(
        console.error
      );
    }, 4000);

    return () => clearInterval(id);
  }, [persistedTestData, setPersistedTestData]);

  console.log(persistedTestData);
```

### Expected Behavior

An element should be **appended** to the `persistedTestData` array every few seconds, even if the page is refreshed in the middle using Browser's refresh button.

### Actual Behavior

After the refresh, although the browser DevTools shows that the elements added before the refresh are still there, the value returned from the hook is an empty array. 4 seconds after the refresh, all elements added before the refresh are gone in IndexDB as if nothing persisted.

**Comment by HazyFish** [comment]
https://github.com/astoilkov/use-db/blob/2e3f5da8bb8752220799259e8bac6072223ccc9f/index.ts#L5-L7

Looks like we never call `dbStorage.getItem` or subscribe any changes from IndexDB in the hook.

**Comment by astoilkov** [comment]
I've started working on fixing this. I'll push and make a new release the moment I'm ready with it.

Thanks for reporting!

**Comment by astoilkov** [comment]
Done. I've published a new release with the fix included.

Again, thanks!
